# SPDX-License-Identifier: GPL-2.0-only
#
# Rockchip Soc drivers
#
obj-$(CONFIG_ROCKCHIP_CPUINFO)  += rockchip-cpuinfo.o
obj-$(CONFIG_ROCKCHIP_GRF) += grf.o
obj-$(CONFIG_ROCKCHIP_PM_DOMAINS) += pm_domains.o
obj-$(CONFIG_MMC_DW_ROCKCHIP)   += sdmmc_vendor_storage.o
obj-$(CONFIG_ROCKCHIP_PVTM)     += rockchip_pvtm.o

obj-y += rk_vendor_storage.o
